DROP TABLE IF EXISTS TABLA_HOTELES;
CREATE TABLE TABLA_HOTELES (
    HOTEL VARCHAR(255) PRIMARY KEY,
    CAPACIDAD INTEGER NOT NULL,
    OCUPACION INTEGER NOT NULL,
    DESTINO VARCHAR(255) NOT NULL
);