DROP TABLE IF EXISTS TABLA_RESERVAS;
CREATE TABLE TABLA_RESERVAS (
    ID INTEGER IDENTITY PRIMARY KEY,
    NIF VARCHAR(9) PRIMARY KEY,
    DESTINO VARCHAR(255) NOT NULL,
    HOTEL VARCHAR(255) NOT NULL,
    HUESPEDES INTEGER NOT NULL,
    HABITACIONES INTEGER NOT NULL,
    FECHAENTRADA DATE NOT NULL,
    FECHASALIDA DATE NOT NULL
);